rc_backhoe_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - swing_joint
    - boom_joint
    - arm_joint
    - bucket_joint
  gains:
    swing_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    boom_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bucket_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1